---
title: "Univariate descriptive statistics of our data"
author: "Group 5 MD"
date: "`r Sys.Date()`"
output: word_document
---

<!-- Posem echo=FALSE perquè les comandes d'R no s'incloguin en el document final -->

```{r, echo=FALSE}
#install.packages("rmarkdown")
#install.packages("rstudioapi")
#library("rmarkdown", "rstudioapi")
```
\
In this document, we provide the basic statistics and plots of our accidents database.

<!-- WARNING: data must have been properly declared before (factors, dates...) -->

```{r, echo=FALSE}
#READ TABLE

setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) #path al dicteroy del script
dd <- readRDS("dd.rds")

```
```{r, echo=FALSE}
#class(dd)
```

\
Dimensions of our dataset:

```{r}
dim(dd)
n<-dim(dd)[1]
K<-dim(dd)[2]

K #Number of variables (columns)
n #Number of instances (rows)
```

\
Check of the variables' names:

```{r}
names(dd)
```

\newpage
Basic descriptive analysis of our variables:

```{r, echo=FALSE}

descriptive<-function(X, nom){
  if (!(is.numeric(X) || class(X)=="Date")){
    frecs<-table(as.factor(X), useNA="ifany")
    proportions<-frecs/n
    #ojo, decidir si calcular porcentages con o sin missing values
    pie(frecs, cex=0.6, main=paste("Pie of", nom))
    barplot(frecs, las=3, cex.names=0.7, main=paste("Barplot of", nom), col=listOfColors)
    print(paste("Number of modalities: ", length(frecs)))
    print("Frequency table")
    print(frecs)
    print("Relative frequency table (proportions)")
    print(proportions)
    print("Frequency table sorted")
    print(sort(frecs, decreasing=TRUE))
    print("Relative frequency table (proportions) sorted")
    print(sort(proportions, decreasing=TRUE))
   }else{
     if(class(X)=="Date"){
       print(summary(X))
       print(sd(X))
       #decide breaks: weeks, months, quarters...
       hist(X, main=paste("Histogram of", nom), breaks="years")
     }else{
       hist(X, main=paste("Histogram of", nom))
       boxplot(X, horizontal=TRUE, main=paste("Boxplot of",nom))
       print("Extended Summary Statistics")
       print(summary(X))
       print(paste("sd: ", sd(X, na.rm=TRUE)))
       print(paste("vc: ", sd(X, na.rm=TRUE)/mean(X, na.rm=TRUE)))
      }
   }
}



# Decide the maximum number of colors you can need in a graph based on your metadata file

listOfColors<-rainbow(39)

dataset<-dd
actives<-c(1:K)

par(ask=TRUE)

for(k in actives){

  print(paste("variable ", k, ":", names(dd)[k] ))
  descriptive(dd[,k], names(dd)[k])
  cat("\n\n\n\n")
}
par(ask=FALSE)

```
